# f=open('another.txt',"w")

# f.write("hello ji !")
# f.close()
f=open("this.txt","w")
f.write("this is nice")
f.write("this is nice")
f.write("this is nice")
f.write("this is nice")
f.write("this is nice")
f.close()